language: java

env:
  global:
    - GRADLE_OPTS=-Xmx256m

before_install:
  - chmod +x gradlew

script:
  - ./gradlew --stacktrace clean install

before_cache:
  - rm -rf $HOME/.gradle/wrapper
  - rm -rf $HOME/.gradle/caches

os:
  - linux

dist: xenial

jdk:
  - oraclejdk11

notifications:
  email: false