---
apiVersion: v1
kind: Pod 
metadata:
  name: mongos-pod
  labels:
    app: mongos-pod
spec:
  containers:
  - name: mongos-router
    image: mongo:4.2.8
    imagePullPolicy: Always
    command: ['sh', '-c', 'mongos --configdb cfgrs/129.82.208.178:27017,129.82.208.179:27017,129.82.208.180:27017 --bind_ip 0.0.0.0 --port 27017']
    ports:
    - containerPort: 27017
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - lattice-166
 

---
apiVersion: v1
kind: Service
metadata:
  name: mongos-service
spec:
  type: NodePort
  selector:
    app: mongos-pod
  ports:
  - nodePort: 30001
    port: 27017 
    targetPort: 27017
  externalTrafficPolicy: Cluster

#---
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: allow-all-egress
#spec:
#  podSelector: {}
#  egress:
#  - {}
#  policyTypes:
#  - Egress
#
#---
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: allow-all-ingress
#spec:
#  podSelector: {}
#  ingress:
#  - {}
#  policyTypes:
#  - Ingress
