---
apiVersion: v1
kind: Service
metadata:
  name: envoy-service
spec:
  type: NodePort
  selector:
    app: envoy-pod
  ports:
  - nodePort: 30002
    port: 80
    targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-deployment
  labels:
    app: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-pod
  template:
    metadata:
      labels:
        app: envoy-pod
    spec:
      dnsPolicy: Default
      containers:
      - name: sustain-envoy
        image: inf0rmatiker/sustain-envoy-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sustain-envoy
                operator: In
                values:
                - "true"
